kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  type: NodePort
  selector:
    app: example-app
  ports:
  - name: web
    nodePort: 30994
    protocol: TCP
    port: 8080
